version: '2'        # 表示该docker-compose.yml文件使用的是Version 2 file format
services:           # Version 2 file format的固定写法，为project定义服务。
  microservice-discovery-eureka:                                  # 指定服务名称
    image: jack/microservice-discovery-eureka:1.0    # 指定服务所使用的镜像
    ports:                                                        # 暴露端口信息
      - "8761:8761"
  microservice-provider-user:
    image: jack/microservice-provider-user:1.0
    links:          # 链接到microservice-discovery-eureka，这边使用的是SERVICE:ALIAS的形式
      - microservice-discovery-eureka:discovery
  microservice-consumer-movie-ribbon-hystrix:
    image: jack/microservice-consumer-movie-ribbon-hystrix:1.0
    links: 
      - microservice-discovery-eureka:discovery
  microservice-gateway-zuul:
    image: jack/microservice-gateway-zuul:1.0
    links: 
      - microservice-discovery-eureka:discovery
  microservice-hystrix-dashboard:
    image: jack/microservice-hystrix-dashboard:1.0
    links: 
      - microservice-discovery-eureka:discovery
  microservice-hystrix-turbine:
    image: jack/microservice-hystrix-turbine:1.0
    links: 
      - microservice-discovery-eureka:discovery