server:
  port: 8010
spring:
  application:
    name: consumer-movie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: true
      circuitBreaker: 50
      fallback:
        enabled: false