server:
  port: 8001

spring:
  application:
    name: provider-user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    #    schema: classpath:schema.sql
    data: classpath:data.sql

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true