spring:
  application:
    name: order
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#swagger:
#  base-package: com.jack

server:
  port: 8082