server:
  port: 8010
spring:
  application:
    name: consumer-movie-ribbon-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



#spring-boot-starter-actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"